steps:
  - read: project_name
    prompt: What is the name of the project?
    default:
      from: path.rootdir

  - update: .devcontainer/devcontainer.json

  - read: php_version

    prompt: Select PHP version
    choices:
      - "8.1"
      - "8.0"
      - "7.4"

  - read: node_version

    prompt: Select Node version
    choices:
      - "18"
      - "16"
      - "14"

  - update: .devcontainer/Dockerfile
