steps:
  - read: project_folder
    prompt: Name the project folder in Docker
    default:
      from: path.rootdir

  - read: web_root
    prompt: Select web server root
    choices:
      - '/web'
      - '/public'
      - '/'
      - Other:
          prompt: Specify the folder name ...

  - read: php_version
    prompt: Select PHP version
    choices:
      - '8.4'
      - '8.3'
      - '8.2'

  - read: composer_version
    prompt: Select Composer version
    choices:
      - '2'
      - '1'

  - read: node_version
    prompt: Select Node version
    choices:
      - '22'
      - '20'
      - '18'

  - read: database
    prompt: Which database
    choices:
      - 'mysql/mysql-server:8.4'
      - 'mysql/mysql-server:8.0'
      - 'mariadb:11'
      - 'mariadb:10'

  - read: post_create_command
    prompt: Command to run after entering dev container
    choices:
      - 'yarn && composer install'
      - 'npm install && composer install'
      - ''
      - Other:
          prompt: Specify command ...

  - copy:
      source: .devcontainer/devcontainer.json
      destination: .devcontainer/devcontainer.json

  - copy:
      source: .devcontainer/Dockerfile
      destination: .devcontainer/Dockerfile

  - copy:
      source: .devcontainer/docker-compose.yml
      destination: .devcontainer/docker-compose.yml

  - remove: .tmplr.yml
