steps:
  - read: project_folder
    prompt: Name the project folder in Docker
    default:
      from: path.rootdir

  - read: web_root
    prompt: Select web server root
    choices:
      - "/web"
      - "/public"
      - "/"
      - Other:
          prompt: Specify the folder name ...

  - read: php_version

    prompt: Select PHP version
    choices:
      - "8.1"
      - "8.0"
      - "7.4"

  - read: composer_version

    prompt: Select Composer version
    choices:
      - "2"
      - "1"

  - read: node_version

    prompt: Select Node version
    choices:
      - "18"
      - "16"
      - "14"

  - read: mysql_version

    prompt: Select MySQL version
    choices:
      - "8.0"
      - "5.7"

  - read: post_create_command
    prompt: Command to run after entering dev container
    choices:
      - "yarn && composer install"
      - "npm install && composer install"
      - ""
      - Other:
          prompt: Specify command ...

  - update: .devcontainer/devcontainer.json
  - update: .devcontainer/Dockerfile
